"""Init tables

Revision ID: b72a7b4966dd
Revises: 
Create Date: 2024-06-25 12:44:20.409030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b72a7b4966dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secret',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('secret_key', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('expire', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secret')
    # ### end Alembic commands ###
